name: test Check Code
on:
  push:
    branches:
      - main # トリガーを指定ブランチに限定する場合

jobs:
  my_job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch at least two commits to access the previous commit

    - name: Get the previous commit SHA
      id: get_previous_commit
      run: |
        PREV_COMMIT=$(git rev-parse HEAD^1)
        echo "PREV_COMMIT=$PREV_COMMIT" >> $GITHUB_ENV

    - name: Checkout the previous commit
      run: git checkout ${{ env.PREV_COMMIT }}

    - name: Execute shell command pre find
      run: |
        echo "pre find."
        find ./ -type f -name "*.py" | xargs -n 1 file > pre.txt

    - name: Checkout now commit
      run: git checkout

    - name: Execute shell command check line
      run: |
        echo "check line."
        find ./ -type f -name "*.py" | xargs -n 1 file > now.txt
        DIFF_LINE=$(diff pre.txt now.txt | wc -l)

        if $DIFF_LINE -ge 0; then
          echo true$DIFF_LINE
        else
          echo false$DIFF_LINE
        fi
